"""Deterministic core of automated remediation PRs.

Given the current ``requirements.txt`` and a *validated* upgrade resolution plan
(from ``upgrade_simulator``), produce the exact pinned-requirements rewrite, a
unified diff, and a human-readable PR body that cites the CVEs each bump
remediates. This is the safe, testable heart of "auto-fix validated upgrade PRs";
the GitHub App layer only has to commit the diff and open the PR.

A fix is only marked ``validated`` when the upgrade simulation reported the plan
feasible -- we never propose an upgrade the simulator could not resolve.
"""

from __future__ import annotations

import difflib
import re
from typing import Any, Optional

_REQ_LINE = re.compile(r"^(?P<name>[A-Za-z0-9._-]+)\s*(?P<extras>\[[^\]]*\])?\s*(?P<spec>[<>=!~].*)?$")


def _normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower().strip("-")


def apply_upgrades(requirements_text: str, steps: list[dict[str, Any]]) -> str:
    """Rewrite pinned versions per the resolution steps, preserving other lines."""
    targets = {_normalize(s["package"]): s.get("to") or s.get("target_version")
               for s in steps if s.get("package")}
    out_lines: list[str] = []
    for raw in requirements_text.splitlines():
        line = raw.rstrip("\n")
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("-"):
            out_lines.append(line)
            continue
        m = _REQ_LINE.match(stripped)
        if not m:
            out_lines.append(line)
            continue
        norm = _normalize(m.group("name"))
        if norm in targets and targets[norm]:
            extras = m.group("extras") or ""
            out_lines.append(f"{m.group('name')}{extras}=={targets[norm]}")
        else:
            out_lines.append(line)
    return "\n".join(out_lines) + ("\n" if requirements_text.endswith("\n") else "")


def _cves_fixed_by_package(assessment: dict[str, Any]) -> dict[str, list[str]]:
    out: dict[str, list[str]] = {}
    for cve in assessment.get("cves", []):
        if cve.get("recommendation") in ("BLOCK", "REVIEW"):
            out.setdefault(_normalize(cve.get("package", "")), []).append(cve.get("cve_id", ""))
    return out


def generate_fix_plan(
    requirements_text: str,
    resolution_steps: list[dict[str, Any]],
    assessment: Optional[dict[str, Any]] = None,
    feasible: bool = True,
    requirements_filename: str = "requirements.txt",
) -> dict[str, Any]:
    new_text = apply_upgrades(requirements_text, resolution_steps)
    diff = "".join(difflib.unified_diff(
        requirements_text.splitlines(keepends=True),
        new_text.splitlines(keepends=True),
        fromfile=f"a/{requirements_filename}",
        tofile=f"b/{requirements_filename}",
    ))

    cves_by_pkg = _cves_fixed_by_package(assessment or {})
    fixed_cves: list[str] = []
    body_lines = ["## Automated dependency remediation", ""]
    if resolution_steps:
        body_lines.append("### Upgrades")
        for s in resolution_steps:
            pkg = s.get("package", "")
            cves = cves_by_pkg.get(_normalize(pkg), [])
            fixed_cves.extend(c for c in cves if c)
            cve_note = f" — fixes {', '.join(c for c in cves if c)}" if cves else ""
            body_lines.append(
                f"- `{pkg}` {s.get('from', '?')} → {s.get('to') or s.get('target_version', '?')}"
                f"{cve_note}"
            )
        body_lines.append("")
    body_lines += [
        "### Validation",
        f"- Upgrade simulation feasible: **{'yes' if feasible else 'no'}**",
        "- [ ] CI passes",
        "- [ ] Tests pass",
        "",
        "_Generated by the Predictive Risk Assessment System._",
    ]

    fixed_cves = sorted(set(c for c in fixed_cves if c))
    title = (
        f"fix(deps): remediate {len(fixed_cves)} vulnerabilit"
        f"{'y' if len(fixed_cves) == 1 else 'ies'}"
        if fixed_cves else "fix(deps): apply validated dependency upgrades"
    )

    return {
        "validated": bool(feasible),
        "changed": new_text != requirements_text,
        "new_requirements": new_text,
        "diff": diff,
        "fixed_cves": fixed_cves,
        "pr_title": title,
        "pr_body": "\n".join(body_lines),
    }
