from __future__ import annotations

from collections import defaultdict

from cve_scanner.models import CVEFinding, ReachabilityResult, RiskScore, ScanResult


def _vulnerable_range(finding: CVEFinding) -> str:
    if finding.fixed_version:
        return f"< {finding.fixed_version}"
    return "unknown"


def build_digest(scan_result: ScanResult, repo_name: str, date_range: str) -> str:
    reachability_map: dict[str, ReachabilityResult] = {
        entry.cve_id: entry for entry in scan_result.reachability
    }
    scores_by_package: dict[str, RiskScore] = {score.package_name: score for score in scan_result.risk_scores}
    findings_by_package: dict[str, list[CVEFinding]] = defaultdict(list)
    for finding in scan_result.cve_findings:
        findings_by_package[finding.package_name].append(finding)

    lines: list[str] = []
    lines.append("# GitHub security alert digest")
    lines.append(f"{repo_name}'s repository security updates from the week of {date_range}")
    lines.append("")
    lines.append(f"## \u26a0\ufe0f  {repo_name} \u2014 Known security vulnerabilities detected")
    lines.append("")
    lines.append("---")
    lines.append("")

    for package_name, findings in findings_by_package.items():
        representative = findings[0]
        vulnerable_range = _vulnerable_range(representative)
        reachability = reachability_map.get(representative.cve_id)
        reachable = reachability.reachable if reachability else False
        reachability_text = "\U0001F534 REACHABLE" if reachable else "\U0001F7E2 Not directly reachable"

        lines.append(f"**Dependency**: {package_name}")
        lines.append(
            f"**Version**: {representative.installed_version} (vulnerable range: {vulnerable_range})"
        )
        lines.append(f"**Upgrade to**: {representative.fixed_version}")
        lines.append(f"**Defined in**: {representative.defined_in}")
        lines.append(f"**Reachability**: {reachability_text}")
        lines.append("")
        lines.append("**Vulnerabilities**:")
        for finding in findings:
            kev_tag = " \U0001f511 KEV" if finding.kev_listed else ""
            lines.append(
                f"- {finding.cve_id} \u2014 {finding.severity.value} severity "
                f"(CVSS {finding.cvss_score}){kev_tag}"
            )
        verdict = scores_by_package.get(package_name)
        if verdict:
            lines.append("")
            lines.append(f"**Risk Verdict**: {verdict.verdict}")
        lines.append("")
        lines.append("---")
        lines.append("")

    total_vulns = len(scan_result.cve_findings)
    critical_high = sum(
        1 for finding in scan_result.cve_findings if finding.severity.value in {"Critical", "High"}
    )
    reachable_packages = sum(
        1
        for package, findings in findings_by_package.items()
        if any(reachability_map.get(f.cve_id) and reachability_map[f.cve_id].reachable for f in findings)
    )

    lines.append("## \U0001f4ca Summary")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total vulnerabilities | {total_vulns} |")
    lines.append(f"| Critical / High | {critical_high} |")
    lines.append(f"| Reachable packages | {reachable_packages} |")
    lines.append(f"| Overall verdict | {scan_result.overall_verdict} |")
    lines.append("")
    lines.append("> Generated by CVE Pre-Upgrade Scanner v1.0.0")

    return "\n".join(lines)
